### ISSUE TITLE
Import only the items you need from lodash instead of the whole library

### ISSUE THREAD

**Issue by dbryantm** [frankthelen/rools#24]
This is more of a suggestion to just import the items you need from lodash instead of the entire library to cut down on size. The only differences would be instead of using:

```
import _ from 'lodash;

_.isBoolean(value);
_.isFunction(value);
```

You would use the following:

```
import { isBoolean, isFunction } from 'lodash;

isBoolean(value);
isFunction(value);
```

It would help on projects that might be using this in lambdas or where they're trying to perform tree shaking. Thanks in advance!

**Comment by frankthelen** [comment]
Good point. Thanks.

**Comment by dbryantm** [comment]
Figured I would ask here, but I submitted a pull request to reduce the package size when importing the project into a webpack based project. Didn't know if you had some time to review it. Thanks!

**Comment by frankthelen** [comment]
Merged. Thanks.
