### ISSUE TITLE
Loading rules from external files

### ISSUE THREAD

**Issue by Onixarts** [frankthelen/rools#26]
Hi, Is it possible, to load rules from external files? I've already load facts from few files, then I wan't do the same with rules, but I don't know how the 'facts' object should be referenced in the rule objects. I'm loading rules using require('rules/rules1.js') in nodejs module.

**Comment by Onixarts** [comment]
Ok, I figured it out.
In calle file.
`let rules = require(fileName)(facts);`
and inside rules files:
```
module.exports = function(facts){
    rules= 
[
    new rools.Rule({name: 'test rule',  when: facts => ... , then: (facts) => ... } })
 ,
    new rools.Rule({name: 'test rule',  when: facts => ... , then: (facts) => ... } })
]
return rules;
}
```

**Comment by frankthelen** [comment]
Yes, that's a possibility. But you don't habe to pass in `facts` because they are always passed to `when` and `then` automatically. So, a file containing rules may look like this:
```js
const { Rule } = require('rools');
const myRule = new Rule({
  name: 'My cool rule',
  when: (facts) => { ... },
  then: (facts) => { ... },
});
module.exports = [
  myRule
];
```
