### ISSUE TITLE
How do I know which rule has fired or which facts has changed?

### ISSUE THREAD

**Issue by Onixarts** [frankthelen/rools#27]
Hi. I'm wonder if there is some way to know which rule was fired or which facts has changed after evaluate. I've wrote nodejs module and I'm using it in node-red, and after change some facts I call evaluate. But then i want to react on some fact's change or rule fired, but the **then** action has only **facts** context, so I can't notify node-red about changes occured.

One solution I've found is to append into special fact array a rule name that fires. After that I'm iterating this fact array and send node-red messages. Is there any easier/dedicated solution for that or lack in rools's functionality?

**Comment by frankthelen** [comment]
Well, it is not really intended to know which rules where fired (except for debugging, of course). If rules are fired, they usually make changes to the facts or do something else in their `then` function. But `evaluate()` lets you know which segments of the facts where changed during evaluation. Maybe that helps.
```js
const { Rools, Rule } = require('rools');
// ...
const rools = new Rools();
// ...
const facts = { user, weather };
const { updated } = await rools.evaluate(facts);
console.log(updated); // e.g., ["user"]
```

**Comment by Onixarts** [comment]
Segment is not enough, because in one segment there can be stored many facts. So each time I call evaluate I have to iterate all segment facts and compare with previous values - so the change fact state can trigger some action.
`then` function can do things, but it is called each time, even when no change occured. In most cases systems are based on events, so the fact value is not as important as change itself.

**Comment by frankthelen** [comment]
Yes, right, the granularity of the facts can be crucial. So, if the updated segments (facts on top-level) are not enough, you might need to additionally diff those segments.
Of course, there is an internal representation of the rules and also whether they have been fired (working memory). But this is not meant to be used outside. Not sure if it useful to expose the working memory after `evaluate()`.
