### ISSUE TITLE
How to use Rools with array of objects?

### ISSUE THREAD

**Issue by dma82** [frankthelen/rools#51]
Hi, 
I was wondering if you could show an example of how to use array of objects both in the 'when' and 'then' parts.
I used a foreach loop in the 'when' part but I'm not sure how I can modify each single object that triggers the conditions in the 'then' part.
Thank you.

**Comment by frankthelen** [comment]
Good point. However, `facts` must be an object (not an array), at least on root level. This is because rools does some optimization on the facts' segments, i.e., the root-level properties of `facts`. Further below, there are no restrictions.
