### ISSUE TITLE
Reading facts are considered as updated

### ISSUE THREAD

**Issue by tatejones** [frankthelen/rools#52]
Hi All,

Maybe I have misunderstood the process of updating facts.  When a fact is read it is considered to be updated.  Is this by design?

observe.js
...
    get(target, property, receiver) {
      onChange(property);
      return Reflect.get(target, property, receiver);
    },
...
The onChange callback is called when a get is made on the proxy (facts).  

Rools.js - line 96
 delegator.set((segment) => { // listen to writing fact segments
        const segmentName = (typeof segment === 'symbol') ? segment.toString() : segment;
        this.logger.debug({ message: `write fact segment "${segmentName}"`, rule: action.name });
        memory.segmentWrite(segment);
      });

If a property on the facts is read during the when: step it is considered to be updated.

Thanks in advance.

**Comment by tatejones** [comment]
Hi Frank,

If I add the following expression to the mood.js rule the test fails.

    if (facts.weather.temperature < 0) {
      facts.user.mood = "brave";
    }



const ruleGoWalking = new Rule({
  name: "go for a walk if mood is great and the weather is fine",
  when: [
    (facts) => facts.user.mood === "great",
    (facts) => facts.weather.temperature >= 20,
    (facts) => !facts.weather.rainy,
  ],
  then: (facts) => {
    if (facts.weather.temperature < 0) {
      facts.user.mood = "brave";
    }
    facts.goWalking = true;
  },
});


  1) Rools.evaluate() / result
       should return evaluation details:

      AssertionError: expected [ 'user', 'weather', 'goWalking' ] to deeply equal [ 'user', 'goWalking' ]
      + expected - actual

       [
         "user"
      -  "weather"
         "goWalking"
       ]
      
      at Context.<anonymous> (test/result.spec.js:32:39)

It believes “weather” has changed when it hasn’t.

**Comment by tatejones** [comment]
Understood. Not a good example. But sometimes you cannot avoid it.

Another example.

Rule1
When:  fact.foodtype === “fresh”
Then: fact.gst = 0

Rule2
When: fact.foodtype === “processed”
Then: fact.gst = 1.1

Rule3
When: fact.foodavailable 
Then: fact.price = fact.exGstPrice * fact.gst

fact.gst is considered changed in Rule3

On the road
***@***.***

**Comment by frankthelen** [comment]
Done. Thanks again.
