### ISSUE TITLE
Access to state from within action

### ISSUE THREAD

**Issue by reneklootwijk** [frankthelen/rools#56]
I use mqtt to send events of my actors and sensors. Each event will be inserted as a fact into the rule engine. However, in my code I keep state of the values of all actors and sensors and I want to be able to access this state from within an action. Assume I keep the state in a global object called devices, then from within an action I try to access the state of a specific device by referring to 
```
devices[device_address].state
```

However, an error is thrown stating the devices object does not exist. When I add the devices object to the fact then I can access the state via 
```
facts.devices[device_address].state
```
but it does not feel right to add the state object to the fact. What is the right way to do this?

**Comment by reneklootwijk** [comment]
Found the issue

**Comment by frankthelen** [comment]
👍
